# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://GilesStrong.github.io/pytorch_inferno/"

git_url = "https://github.com/GilesStrong/pytorch_inferno/tree/master/"

def custom_doc_links(name): return None
