# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PseudoData": "00_pseudodata.ipynb",
         "paper_sig": "00_pseudodata.ipynb",
         "paper_bkg": "00_pseudodata.ipynb",
         "ModelWrapper": "01_model_wrapper.ipynb",
         "DataSet": "02_data.ipynb",
         "WeightedDataLoader": "02_data.ipynb",
         "DataPair": "02_data.ipynb",
         "get_paper_data": "02_data.ipynb",
         "AbsCallback": "03_callback.ipynb",
         "LossTracker": "03_callback.ipynb",
         "EarlyStopping": "03_callback.ipynb",
         "SaveBest": "03_callback.ipynb",
         "PredHandler": "03_callback.ipynb",
         "PaperSystMod": "03_callback.ipynb",
         "GradClip": "03_callback.ipynb",
         "to_device": "04_utils.ipynb",
         "device": "04_utils.ipynb",
         "to_np": "04_utils.ipynb",
         "init_net": "04_utils.ipynb",
         "plt_style": "05_plotting.ipynb",
         "plt_sz": "05_plotting.ipynb",
         "plt_cat_pal": "05_plotting.ipynb",
         "plt_tk_sz": "05_plotting.ipynb",
         "plt_lbl_sz": "05_plotting.ipynb",
         "plt_title_sz": "05_plotting.ipynb",
         "plt_leg_sz": "05_plotting.ipynb",
         "plot_preds": "05_plotting.ipynb",
         "plot_likelihood": "05_plotting.ipynb",
         "bin_preds": "06_inference.ipynb",
         "get_shape": "06_inference.ipynb",
         "get_paper_syst_shapes": "06_inference.ipynb",
         "get_likelihood_width": "06_inference.ipynb",
         "interp_shape": "06_inference.ipynb",
         "calc_nll": "06_inference.ipynb",
         "jacobian": "06_inference.ipynb",
         "calc_grad_hesse": "06_inference.ipynb",
         "calc_profile": "06_inference.ipynb",
         "VariableSoftmax": "07_inferno_exact.ipynb",
         "AbsInferno": "07_inferno_exact.ipynb",
         "PaperInferno": "07_inferno_exact.ipynb",
         "InfernoPred": "07_inferno_exact.ipynb",
         "AbsApproxInferno": "07_inferno_interp.ipynb",
         "ApproxPaperInferno": "07_inferno_interp.ipynb"}

modules = ["pseudodata.py",
           "model_wrapper.py",
           "data.py",
           "callback.py",
           "utils.py",
           "plotting.py",
           "inference.py",
           "inferno.py"]

doc_url = "https://GilesStrong.github.io/pytorch_inferno/"

git_url = "https://github.com/GilesStrong/pytorch_inferno/tree/master/"

def custom_doc_links(name): return None
